fix "glibc cannot be compiled without optimization" when building glibc headers
Date: Sun, 6 May 2007 18:47:55 -0400 (EDT)
From: "Robert P dot  J dot  Day" <rpjday at mindspring dot com>
To: crosstool list <crossgcc at sourceware dot org>
Subject: [SOLVED] #error "glibc cannot be compiled without optimization"
Message-ID: <Pine.LNX.4.64.0705061841280.20709@localhost.localdomain>

  slowly tracking down the last couple issues with this x86_64 build
and, in the last pass, i had two errors of the form:

  error: #error "glibc cannot be compiled without optimization"

while trying to build the glibc headers.  as a quick hack, i made the
following change in crosstool.sh:

[snip]

  i have no idea whether that was the *proper* fix but it got rid of
those two diagnostic messages.  (those errors weren't fatal to the
build, but i figured it was worth dealing with them, anyway.)

  was that the right approach?  is that something that should be added
to crosstool.sh?

rday

p.s.  i'm still getting all those error: #error "TLS support is
required." diagnostics.  still trying to figure out what to do about
those.

man, it's been a long day.

rday
--
========================================================================
Robert P. J. Day
Linux Consulting, Training and Annoying Kernel Pedantry
Waterloo, Ontario, CANADA

http://fsdev.net/wiki/index.php?title=Main_Page
========================================================================

--
For unsubscribe information see http://sourceware.org/lists.html#faq